### ISSUE TITLE
toml-lint CLI?

### ISSUE THREAD

**Issue by danielmarquard** [gscho/toml-lint#1]
So many linting tools support CLI. Interesting to see a web-based one. Any plans to make this into a CLI tool? Thanks!

**Comment by gscho** [comment]
toml-lint isn't really a linter because it is not opinionated about how toml is written or formatted. Its a pretty print/syntax checker along the lines of jsonlint.com or yamllint.com. Not sure why those websites are named "lint" but I just followed the same pattern.
