### ISSUE TITLE
dates (sans time) are flagged as invalid

### ISSUE THREAD

**Issue by jvickroy** [gscho/toml-lint#2]
For example:
`ld1 = 1979-05-27`
is flagged as invalid ( **Expected "T" but end of input found.**  ).

**Comment by gscho** [comment]
@jvickroy toml-lint currently supports the toml standard version 0.4. 
It relies on https://github.com/jakwings/toml-j0.4 for parsing the TOML.

I'll consider changing out that library when time permits.

**Comment by jvickroy** [comment]
Thanks for responding.  toml-lint is great; thanks for making it available.

**Comment by jvickroy** [comment]
Great!  Thanks for updating the toml parser version used by toml-lint.
